plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
AllCops:
  Exclude:
    - bin/bundle
    - bin/rake
    - bin/rspec
    - bin/rubocop
    - tmp/**/*
  NewCops: enable
  TargetRubyVersion: 3.2
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
