name: integrate
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - run: bin/rake build
      - run: bin/rake build:native
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo clippy
  oxfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx oxfmt --check
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.3
          - 3.4
          - 4.0
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bin/setup
      - run: bin/rake spec
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - run: bin/setup
      - run: bin/rake rubocop
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo fmt --check
